### ISSUE TITLE
Improve metadata dump to be faster and enable immediate dump vs cron job (was: cache issue: can't install newer version of package)

### ISSUE THREAD

**Issue by mindplay-dk** [composer/packagist#524] opened 2015-06-16 13:24 UTC
I was unable to install version 1.2 of this package - I even tried a clean folder and `composer init` to create a project from scratch, it wouldn't install:

```
C:\workspace\test\crap>composer require mindplay/filereflection=~1.2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mindplay/filereflection could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

Version 1.2 [has been tagged](https://github.com/mindplay-dk/filereflection/releases) and Packagist [does list the new version](https://packagist.org/packages/mindplay/filereflection).

After discovering that it installed without problems on a different system, I went ahead and deleted the `%LOCALAPPDATA%/Composer/files/mindplay/filereflection` folder - repeating the command above, it installed without problems, so there is almost definitely a cache problem.

Probably related to #941 (which was closed for comments.)

I never deleted any tags or did anything weird to this repository, as far as I know, so I don't know how it got into this state.

I archived `4e16b66d566f05c8687705408662094483848c0d.zip` which was the only file in the folder I deleted, if that's helpful. Inside the archive is a folder named `mindplay-dk-filereflection-4e16b66` containing what appears to be release 1.1 of that package.

It cost me a lot of time already, so let me know if I can provide any further information or do anything else to help debug this issue - it sounds like it may have already been biting others (?)

**Comment by stof** [comment] 2015-06-16 13:37
This is weird. the zip archive is the downloaded dist. But Composer will use the dist cache only when installing the code. Your issue happens during the dependency resolution, so much before this point.

**Comment by mindplay-dk** [comment] 2015-06-17 16:44
@stof so this would have been an issue with `composer.lock` potentially? I didn't archive that. dang.

**Comment by Seldaek** [comment] 2015-06-20 20:40
@mindplay-dk my guess is you just tried to use it too quickly and by the time you tried on the other machine and then played around with the cache it started working.. There is a delay of up to 1min between packagist updating and composer seeing the changes. Given the lack of reproducibility I am going to close this sorry but if it's not that I don't know what it is.

**Comment by mindplay-dk** [comment] 2015-06-21 06:44
Trying to figure this out went on for at least half an hour, so a 1 minute
cache doesn't explain it. I managed to update the same codebase on a
different system, and some time passed after that and still couldn't
update.

If this happens again, I will take a snapshot of the complete project
state, and try moving it to a different system - then we'll know if it's
the project state or system state causing it at least.

This one minute cache you mention, I believe that could be the source of a
much more frequent annoyance - I often push a new tag, and I see the tag
listed on Packagist, but I have to try composer update multiple times and
wait before I can install it. This happens several times every day. I doubt
the one minute cache is giving you any net savings here, since people will
keep aggressively repeating the update and hitting the server for other
packages repeatedly until they get the update they want...?

**Comment by Seldaek** [comment] 2015-06-22 15:59
Yeah it's not really a cache per se but just due to the way we dump the json metadata on disk, right now it's a every minute cron job, it might be feasible to update more frequently but it'd need a rewrite of that logic to work in a more "streamed" way, especially updating the listings would need some rework to perform better.

I'll reopen to keep that in mind.

**Comment by stof** [comment] 2021-02-01 11:44
@Seldaek isn't this solved for the v2 metadata now ?

**Comment by Seldaek** [comment] 2021-04-09 14:44
It wasn't. But it is now, for Composer 2 metadata updates are now happening within 3-5seconds 🥳

**Closed** 2021-04-09 14:43 UTC
Labels: Feature
