### ISSUE TITLE
Gitlab hosted public repository not updating

### ISSUE THREAD

**Issue by luka8088** [composer/packagist#916] opened 2018-05-24 22:43 UTC
A few days ago Packagist stopped updating my Gitlab-hosted repositories.

Examples:
https://packagist.org/packages/phlint/phlint
https://packagist.org/packages/phlint/phif

When I am logged in to Packagist I get a message: "This package is in a broken state and will not update anymore. Some branches contain invalid data and until you fix them the entire package is frozen. Click "Update" below to see details."

Note that there were recently no changes to `composer.json` file in either repositories.
Also note that Gitlab recently made some GDPR related changes where they made everyone accept new terms before they can continue using Gitlab. Although seemingly unrelated I started experiencing the issue at the same time I suspect it could be related. However I get no info back from Packagist on why it can't update and even the info I do get back about broken state seems misleading.

Do you have any suggestion about how to better debug this issue? Thanks!

**Comment by dyszczo** [comment] 2018-05-25 07:44
I have problem with public gitlab repositories too

Examples: 
https://packagist.org/packages/wpdesk/wp-builder
https://packagist.org/packages/wpdesk/wp-settings

**Comment by grola** [comment] 2018-05-25 07:46
I have same problem with my public gitlab repositories.

**Comment by Geolim4** [comment] 2018-06-03 22:59
@dyszczo Did you configured webhooks on Gitlab ?

**Comment by Seldaek** [comment] 2018-06-06 13:44
GitLab blocked their API access until you accept the new GDPR terms, that might be the cause for this. Anyway the packages listed look fine now so closing this. Please do tell if you still have issues.

**Closed by Seldaek** 2018-06-06 13:44 UTC
