### ISSUE TITLE
Don't auto collapse the readme on package pages

### ISSUE THREAD

**Issue by PeeHaa** [composer/packagist#627] opened 2015-12-28 15:20 UTC
On package package don't auto collapse the read me content. It adds nothing but an extra click.

Especially considering that most of the time the actual info you want / are looking for is behind the "read more". AFAICS there is no reason at all to have the feature there.

Nothing is lost when dropping the auto collapse or even dropping the collapse entirely for the read me. Even on mobile it's the last item on the page (excluding the footer).

**Comment by alcohol** [comment] 2015-12-28 15:22
Obvious duplicate of #607.

**Closed by alcohol** 2015-12-28 15:22 UTC

**Comment by PeeHaa** [comment] 2015-12-28 15:24
Ugggh yes obvious...

My issue search failed somewhow. I am bad and I should feel bad

**Comment by alcohol** [comment] 2015-12-28 15:25
I did not mean to come across rude nor did I fault you for not finding the duplicate yourself. I'm simply stating that they are **very** similar in context and hence this is why I closed the issue.

**Comment by PeeHaa** [comment] 2015-12-28 15:27
Oh don't get me wrong ;-) I never thought you were rude in any way.

I was just bothered by myself not finding the open issue.
