### ISSUE TITLE
Emoji in package description breaks packagist

### ISSUE THREAD

**Issue by evert** [composer/packagist#622] opened 2015-12-14 22:28 UTC
I added a 📅 in the description of my calendaring-related composer package. Manually hitting update on the packagist website yields:

    [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'UPDATE package SET description = ? WHERE id = ?' with params ["\ud83d\udcc5 The VObject library for PHP allows you to easily parse and manipulate iCalendar and vCard objects", 2671]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x93\x85 T...' for column 'description' at row 1

**Comment by staabm** [comment] 2015-12-14 23:03
Duplicate of https://github.com/composer/packagist/issues/608 ?

**Comment by evert** [comment] 2015-12-14 23:04
Ah yea possibly. I've leave it up to them to decide if it's the same bug =)

**Comment by alcohol** [comment] 2015-12-15 08:37
Yeah it's a duplicate. It requires changing the database schema of Packagist, which is not something we can just do casually. But we are aware of the issue, and it will be fixed :)

**Closed by alcohol** 2015-12-15 08:37 UTC

**Comment by staabm** [comment] 2016-01-04 19:47
@evert just to let you know. It seems the underlying issue was fixed

**Comment by evert** [comment] 2016-01-04 20:07
cool! also released on packagist.org ?

**Comment by Seldaek** [comment] 2016-01-04 21:11
Yup

**Comment by evert** [comment] 2016-01-04 21:19
whoo!
