### ISSUE TITLE
Site Search ( or composer search ) does not search

### ISSUE THREAD

**Issue by cedamorim** [composer/packagist#595] opened 2015-10-15 19:33 UTC
When I try to do any research, it is always returned the same result (all records).

**Comment by rchouinard** [comment] 2015-10-16 02:11
I'm experiencing the same. Looks like the changes to WebContoller in 46bc2d4 might have broken it.

**Comment by chlabelek** [comment] 2015-10-16 05:21
Same. When typing, the search query is "q" instead of "tags".

**Comment by alcohol** [comment] 2015-10-16 08:22
Cannot reproduce. Searching works just fine for me :\

**Comment by chlabelek** [comment] 2015-10-16 08:22
Fixed indeed.

**Closed** 2015-10-16 10:20 UTC
