### ISSUE TITLE
Github commits not successfully triggering packagist

### ISSUE THREAD

**Issue by Danack** [composer/packagist#572] opened 2015-08-22 21:14 UTC
For several projects that I have set up recently, the Packagist Webhook I have setup on Github for the project appears to be configured correctly on Github, but no pushes appear to be reaching Packagist, and it still has the message "This package is not auto-updated."

I've checked the setup for them quite a few times, and obviously it could still be me doing something dumb but I can't see anything different to how my other projects are setup that are successfully working.

Doing the 'test service' in Github gives the message "Okay, the test payload is on its way." but there is no update on the packagist end.

Incidentally, I recently linked my Github account to my packagist account. That may or may not be totally unrelated.

One of the projects that has this problem is:

https://github.com/Danack/Tier
https://packagist.org/packages/danack/tier

Obviously there is a work-around of going to Packagist and hitting the 'update' button for each package after doing a commit/tag, but it would be nice to have the automatic updating working.

**Comment by alcohol** [comment] 2015-08-22 22:45
You added your packagist API token?

**Comment by Seldaek** [comment] 2015-08-22 23:04
Common issues:

- you used the packagist *email* or *github* username instead of the **packagist username** in the username field
- you borked your API token copy paste somehow (unlikely I think)
- you added a domain name with some sort of weirdness instead of leaving that field empty
- GitHub just messed up. It seems it happens sometimes and that deleting and re-creating the hook entirely helps fix it. Worth a shot.

**Comment by Danack** [comment] 2015-08-24 22:05
So - I think the issue was that the url I had setup did not match exactly.

Deleting the packages from Packagist and re-creating them with the exact spelling as the git repo made them work.

For one of the projects I was having trouble with, I had also managed to set it up with a non-https URL i.e. http://www.github.com/danack/caching instead of https://github.com/Danack/Caching

So I guess this is turning into a feature request to either grab the canonical when setting up a repo, or allow matching based on normalized urls, or just prevent dumbos like me from being able to setup an entry in packagist in a way that is never going to be able to process the push hook from Github.

**Comment by stof** [comment] 2015-08-25 12:41
well, http vs https is handled already IIRC. but you have an extra www in your case.

**Comment by Seldaek** [comment] 2015-08-25 22:52
Yeah we do get the canonical for github repos but I think the issue is actually that using www.github.com made it skip the github driver and instead just use the repo as a plain git repo, which skipped the canonical step. That'll have to be fixed in composer.

**Closed** 2015-08-31 09:59 UTC
Labels: Support
