### ISSUE TITLE
Feature Request: PHP Version Statistics Per Package?

### ISSUE THREAD

**Issue by donatj** [composer/packagist#1079] opened 2020-04-23 20:49 UTC
I find the statistics of [what versions of my packages](https://packagist.org/packages/donatj/phpuseragentparser/stats#v0.15.0) per date are installed very useful.  

It would be _remarkably_ useful to know _installs by PHP version_ on a similar chart by date - it would let me know which of my projects I could finally drop 5.x support for.

I don't know if this info is available to packagist propper - or if that would require a composer update - but I think this would be a very useful feature to the community at large in the name of moving PHP packages forward.

**Comment by Seldaek** [comment] 2020-04-24 12:15
This is technically feasible but a lot of effort so not quite sure if/when we will get to it. There are other much more important things to work on still at the moment.

Closing as duplicate of https://github.com/composer/packagist/issues/1054 though.

**Closed by Seldaek** 2020-04-24 12:15 UTC
