### ISSUE TITLE
Corrupt data in repo-apac-sin-1.packagist.org

### ISSUE THREAD

**Issue by mstrelan** [composer/packagist#1135] opened 2020-11-09 23:10 UTC
The contents of `https://repo.packagist.org/p2/jcalderonzumba/mink-phantomjs-driver.json` on `repo-apac-sin-1.packagist.org (51.79.162.48)` contains the json for `jcbrand/converse.js` instead of `jcalderonzumba/mink-phantomjs-driver.json`. This leads to the following error trying to require `jcalderonzumba/mink-phantomjs-driver:^0.3`

```
[InvalidArgumentException]                                                              
Could not find package jcalderonzumba/mink-phantomjs-driver in a version matching ^0.3  
```

See curl requests against different IPs returning different output:

**51.79.162.48**

```
$ curl https://repo.packagist.org/p2/jcalderonzumba/mink-phantomjs-driver.json -s --resolve repo.packagist.org:443:51.79.162.48 | head -c 100
{"packages":{"jcbrand/converse.js":[{"name":"jcbrand/converse.js","description":"Browser based XMPP
```

**54.39.179.221**

```
$ curl https://repo.packagist.org/p2/jcalderonzumba/mink-phantomjs-driver.json -s --resolve repo.packagist.org:443:54.39.179.221 | head -c 100
{"packages":{"jcalderonzumba/mink-phantomjs-driver":[{"name":"jcalderonzumba/mink-phantomjs-driver",
```

**Comment by Seldaek** [comment] 2020-11-18 21:02
Fixed now, sorry I missed this issue for so long. Duplicate of https://github.com/composer/composer/issues/9481#issuecomment-728328511 btw

**Closed by Seldaek** 2020-11-18 21:02 UTC

**Comment by mstrelan** [comment] 2020-11-19 00:33
Perfect, thank you.
