### ISSUE TITLE
Github signup

### ISSUE THREAD

**Issue by lakshmaji** [composer/packagist#780] opened 2017-04-13 06:39 UTC
Hi There,

I have signed up to packagist using github authorization. I just wanted to change my user name but it was asking me the current password. How can i get the password as I have done signup through Github authorization ??

**Comment by stof** [comment] 2017-04-13 07:32
duplicate of https://github.com/composer/packagist/issues/359

**Comment by lakshmaji** [comment] 2017-04-13 10:37
Hi @stof ,
That works fine, but the github authenticated users requires this ???

**Comment by stof** [comment] 2017-04-13 10:47
well, the fact that it should not be requried for them is precisely what #359 is about (except that nobody contributed a fix for it yet, and this is a not high-priority task for maintainers as there is a workaround so they spent their time on more important tasks related to Composer and Packagist)

**Comment by lakshmaji** [comment] 2017-04-13 10:57
@stof Thanks

**Closed** 2017-04-13 10:56 UTC
