### ISSUE TITLE
There is a problem with `extensions` turning pages

### ISSUE THREAD

**Issue by tw2066** [composer/packagist#1472] opened 2024-10-28 07:32 UTC
Unable to turn the page

https://packagist.org/extensions?page=2

<img width="564" alt="image" src="https://github.com/user-attachments/assets/4de25e53-40c3-449b-a72d-8c021dacaf71">

**Comment by TimWolla** [comment] 2024-10-28 14:37
Duplicate of #1469

**Closed** 2024-10-28 21:56 UTC
