### ISSUE TITLE
No search results for phpcompatibility/php-compatibility

### ISSUE THREAD

**Issue by InvisibleSmiley** [composer/packagist#1163] opened 2021-02-16 15:19 UTC
Steps to reproduce:
1. See that https://packagist.org/packages/phpcompatibility/php-compatibility exists
2. See that https://packagist.org/search.json?q=phpcompatibility/php- includes phpcompatibility/php-compatibility
3. See that https://packagist.org/search.json?q=phpcompatibility/php-compatibility produces an empty result set

If I'm making a mistake querying the API there please advise.
It worked with lots of packages for me, just not for this one.

**Comment by stof** [comment] 2021-02-16 16:34
The weird thing is that https://packagist.org/search.json?q=phpcompatibility/phpcompatibility (without the dash) will still find it though. But putting any char after the `-` won't find any result.

**Comment by Seldaek** [comment] 2021-05-20 15:13
This is really weird, and I can't explain it with the knowledge I have from the algolia search.. Maybe @julienbourdeau can help us out?

**Comment by julienbourdeau** [comment] 2021-06-28 12:14
Sorry @Seldaek I didn't see your ping. Can you give me support access so I can look at the configuration?

My first thought is that it's because of [Advanced Syntax](https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/) which turns the query into _"has `phpcompatibility/php` but doesn't have `compatibility`. I'll have a look what's the way way to fix it.

**Comment by Seldaek** [comment] 2021-06-28 12:17
@julienbourdeau granted you access 👍🏻 Thanks for having a look :)

**Comment by InvisibleSmiley** [comment] 2021-11-17 10:59
ping

Please let me know if/how I can help

**Comment by Seldaek** [comment] 2021-11-17 12:40
@julienbourdeau I don't think it's advanced syntax as the docs indicate `search-engine matches records containing “search” and “engine” (there’s no exclusion because the minus (-) is in the middle of the word)`

Also it is found with `phpcompatibility/php-compatibilitz`, `phpcompatibility/php-compatibilityz` etc.. Only the exact match fails to return it.

A search for `wyrihaximus/react-parallel-runtime` for example returns the package matching exactly though.

**Comment by chr-hertel** [comment] 2022-02-19 19:16
But it appears as result if you escape the minus: https://packagist.org/search.json?q=phpcompatibility/php\-c
And while trying to understand this issue, I figured out that it is coupled to the `/` being part of the `separatorsToIndex` config as this is only reproducable in combination with `/`

so, one fix for this would be to add `-` to the `separatorsToIndex` in algolia's index config.
what would make sense to me as this is part of the name.

i'm unsure about other consequences though

**Comment by Seldaek** [comment] 2022-02-19 19:22
Ah nice find. Could be a fix, but I think it may be better to escape them before sending to algolia, unless they're preceded by a space, so that you could still do `foo/bar -bla` to exclude `bla` from results.

**Comment by chr-hertel** [comment] 2022-02-20 11:50
yup, just checked, that exclusion behavior would break with changing that setting!

tried this escaping thing in https://github.com/chr-hertel/packagist/commit/ade38e90ab32651ca36eacecad9d4239492010fb
works for backend as expected, but failed on js part - but that's certainly more due to my js skills, maybe someone can take over (commit is on top of #1238)

**Comment by Seldaek** [comment] 2022-03-18 08:40
Fixed in https://github.com/composer/packagist/commit/0d08b0f96df8ada39fcfcd2678cd2e145dc01923

**Comment by Seldaek** [comment] 2022-03-18 08:40
The way I ended up fixing it btw is escaping `-` to `--`, I am not entirely sure why this works but it seems to do the trick..

**Closed by Seldaek** 2022-03-18 08:40 UTC
Labels: Bug
