### ISSUE TITLE
Cannot change password when registering with github

### ISSUE THREAD

**Issue by billduapp** [composer/packagist#598] opened 2015-10-21 14:35 UTC
hi,

we skipped the classic registration where you set a password and clicked sign in with github directly.
an account was created, but now it's impossible to change password. and without a password we can't edit the settings.

we were thinking that maybe an email containing some auto generated password will be sent, but after few hours of waiting it seems it's not going to arrive

thanks for help

**Comment by alcohol** [comment] 2015-10-21 15:40
Duplicate of #359

**Closed by alcohol** 2015-10-21 15:40 UTC
