### ISSUE TITLE
Auto-mark abandoned in packagist.org based on flag

### ISSUE THREAD

**Issue by dereuromark** [composer/packagist#870] opened 2018-02-05 14:49 UTC
https://github.com/composer/packagist/issues/192 allows to mark repos abandoned via composer.json
(e.g. https://github.com/spryker/sales-aggregator/blob/master/composer.json#L5 )

This should auto-mark them as such in packagist.org without the need of the manual button post there.
Once detected in master as enabled that could happen automatically :)

**Comment by stof** [comment] 2018-02-05 18:32
#192 allows Packagist to expose this abandoned flag to composer actually, based on the button push.
AFAIK, it was not meant to use it in the composer.json directly.

**Comment by dereuromark** [comment] 2018-02-05 23:51
I would find the other way more intuitive. People can then also PR this.

**Comment by Seldaek** [comment] 2018-06-06 13:13
I tried to implement this but the issue is we can't really allow the flag to be removed by removing it from composer.json as we can't differentiate between a flag that was removed and one that was never there (which would un-abandon packages that have been abandoned in the UI when they get updated). So as such I'd rather avoid further trouble and mark this as won't fix.

**Closed by Seldaek** 2018-06-06 13:13 UTC
