### ISSUE TITLE
session_start(): Failed to read session data: user (path:) 

### ISSUE THREAD

**Issue by geekbaba** [composer/packagist#931] opened 2018-08-04 08:06 UTC
The following error is installed in the php7.2 environment.

[error] 7500#0: *53 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Failed to read session data: user (path:) in packagist/app/cache/prod/classes.php on line 66
PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: ) in packagist/app/cache/prod/classes.php on line 66" while reading response header from upstream, client: 127.0.0.1, server: packagist.medbanks.cn, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "packagist.mydomain.com"

**Comment by mhetru** [comment] 2018-08-16 16:02
after i make
``chmod 777 /var/lib/php/sessions
and
``rm -rf app/cache/*
and
``service php7.1-fpm restart

i got an another error :

> 
[Thu Aug 16 17:59:19.075231 2018] [proxy_fcgi:error] [pid 26326:tid 139660449801984] [client 194.254.x.x:57058] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/packagist.univ.fr/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 155\nPHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /var/www/packagist.univ.fr/htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 155\n'

**Comment by stof** [comment] 2018-08-16 16:02
I think the issue is that your folder configured to write sessions (`/var/lib/php/sessions` according to the error message) might not be accessible to your webserver

**Comment by mhetru** [comment] 2018-08-16 16:05
the directory sessions of PHP have all permissions:
``
root@php70-1:/var/lib/php# ll
total 8
drwxr-xr-x 4 root root 4096 févr. 12  2018 modules
drwxrwxrwt 2 root root 4096 août  16 18:04 sessions
``

**Comment by mhetru** [comment] 2018-08-16 16:12
it is a particularity introduced with PHP 7.1.
The load session mustn't return null but an empty string.
https://stackoverflow.com/questions/48245296/php-custom-session-handler-problems-php-7-1?rq=1

**Comment by stof** [comment] 2018-08-16 16:14
@mhetru the Symfony session handling code is running fine in production since a long time on PHP 7.1 and PHP 7.2. So I doubt your issue is the same than the SO answer you are linking to (even though PHP displays the same error message, which it can display for many things)

Btw, a `sessions` folder owned by `root` looks suspicious to me. I hope your webserver does not run the PHP code as `root`

**Comment by mhetru** [comment] 2018-08-16 16:46
i have found a solution:

i have changed this line
> handler_id: snc_redis.session.handler
with this line:
> handler_id: ~
in app/config/config_prod.yml:

and it works fine!

**Comment by stof** [comment] 2018-08-16 17:37
hmm, then report it to the SncRedisBundle.

I indeed forgot that Packagist was using a third-party session handler.

**Comment by stof** [comment] 2018-08-16 17:37
oh, and make sure your redis server is working of course.

**Comment by mhetru** [comment] 2018-08-17 07:39
hello, i don't use redis server for session storage but native session of PHP.

**Comment by stof** [comment] 2018-08-17 10:46
Well, before you changed the line in the config, you *were* using redis

**Comment by mhetru** [comment] 2018-08-18 09:34
No i have not a redis server. So i disable the session handler for redis in this config file.

**Comment by geekbaba** [comment] 2018-08-20 10:18
I just downgrade the PHP Version to 7.1 , it works! I don't know the real reason

**Comment by mhetru** [comment] 2018-08-23 17:59
Finally i have installed an old version of packagist (an old version git cloned 11 march 2015) and it works!
I had to install this old version of packagist because the fresh last version gitcloned don't work without redis server. Even i disable the session handler redis... I could not publish packages. 
It's a shame to have imposed the use of the server redis

**Comment by stof** [comment] 2018-08-23 18:04
Well, packagist uses Redis not only for storing the session, but also for storing other infos (for instance for storing download stats).

**Comment by mhetru** [comment] 2018-08-23 18:16
ok nice, thanks for your answer.
but it would be cool to be capable to disable the redis server if we don't want to store stats, download, stats and others datas... ;-)

**Comment by stof** [comment] 2018-08-23 18:26
The packagist code is about running packagist.org. It is not meant for re-use, as documented at the beginning of the README: https://github.com/composer/packagist#packagist

So this is out of the scope of the project (it would require making the codebase more complex by wrapping all places using redis).
Thus, it would be quite complex, as Redis is now used for many things (and so your Packagist setup would probably not work fine)

**Comment by mhetru** [comment] 2018-08-23 18:43
Thanks for your precisions 👍

**Comment by mhetru** [comment] 2018-08-25 11:58
even with a redis server installed, the last version of packagist work good : i can submit a package, but when i go on the page of the package, i see multiples nonstop requests on the URL "/jobs/long-id"... i forgot something in the configuration?

**Comment by Seldaek** [comment] 2018-08-25 14:30
Closing as we do not provide support for running your own instance of the code. Feel free to keep discussing if you like though.

**Closed by Seldaek** 2018-08-25 14:30 UTC

**Comment by Dygear** [comment] 2022-11-07 23:59
> it is a particularity introduced with PHP 7.1. The load session mustn't return null but an empty string.
> 
> http://php.net/manual/en/function.session-start.php#120589 https://stackoverflow.com/questions/48245296/php-custom-session-handler-problems-php-7-1?rq=1

Just wanted to say that this comment helped me fix a problem in my custom session handler. If you have a custom session handler that uses sqlite and get this error it may be because you've returned false (or null) from your read function. If you replace that with an empty string you'll be get rid of the incorrect error message.
