### ISSUE TITLE
Packagist does not show my package in search results

### ISSUE THREAD

**Issue by mbajda** [composer/packagist#815] opened 2017-09-19 13:41 UTC
I've recently (yesterday) added my package to packagist. The package name is:

> mbajda/yahoo-weather

I can use a 'require' key in composer.json to add a requirement for this package
```
"require": {
    "mbajda/yahoo-weather": "dev-master"
}
```
and the downloading works properly. What does not work, is that when I try to search for that package in the Packagist search box, the package cannot be found - I don't see it in the search results.

**Comment by localheinz** [comment] 2017-09-19 13:50
Can confirm this issue!

🤓

**Comment by mrcnpdlk** [comment] 2017-09-19 18:10
I also have this problem. My new package is not searchable after adding to the packegist.

**Comment by localheinz** [comment] 2017-09-20 08:53
Actually, I have to revise my comment - not only can I confirm that the package `mbajda.yahoo-weather` cannot be found, but also that a package I submitted myself yesterday cannot be found.

Shows up on https://packagist.org/users/localheinz/packages/:

![screen shot 2017-09-20 at 10 51 34](https://user-images.githubusercontent.com/605483/30635121-bf569cd4-9df1-11e7-967c-b1429f318f76.png)

Does not show up in search results at https://packagist.org/?q=factory%20muffin%20definition.

@mbajda 

Your package also shows up under the list of your packages, though: https://packagist.org/users/mbajda/packages/

**Comment by localheinz** [comment] 2017-09-20 08:54
Possibly related to #805.

**Comment by localheinz** [comment] 2017-09-20 08:59
Not sure if it is related, but if I search for `localheinz/test-util`, https://packagist.org/?q=localheinz%20test%20util shows **0** downloads>

![screen shot 2017-09-20 at 10 57 56](https://user-images.githubusercontent.com/605483/30635403-96948698-9df2-11e7-86d5-65914be04ebc.png)

However, I can confirm that I have downloaded it a couple of times, which can also be seen at https://packagist.org/packages/localheinz/test-util:

![screen shot 2017-09-20 at 10 58 54](https://user-images.githubusercontent.com/605483/30635457-bb9966ac-9df2-11e7-998b-9b99a19a312c.png)

Maybe it's just the indexing that is behind or something?

**Comment by stof** [comment] 2017-09-20 16:08
I suspect that the indexing was failing due to the issue fixed in https://github.com/composer/packagist/pull/820#issuecomment-330901506

**Comment by Seldaek** [comment] 2017-09-21 14:46
Fixed now, sorry about that.

**Closed by Seldaek** 2017-09-21 14:46 UTC

**Comment by localheinz** [comment] 2017-09-21 16:35
Thanks a ton, @Seldaek!
