### ISSUE TITLE
bug in abandon message

### ISSUE THREAD

**Issue by clxmstaab** [composer/packagist#1208] opened 2021-09-15 14:37 UTC
I guess there is a bug in the "specific" linked package

see https://packagist.org/packages/symplify/symplify

![image](https://user-images.githubusercontent.com/47448731/133454066-fb9401e3-fae7-4ec4-bc6e-a42dacf57da3.png)

**Comment by stof** [comment] 2021-09-15 14:47
Well, the maintainer said to use the `specific` package as replacement, which is what this link tries to do. The issue is that what was provided was not an actual package name.

**Comment by clxmstaab** [comment] 2021-09-15 14:50
@TomasVotruba sounds like there is something fishy in the project then?

**Comment by TomasVotruba** [comment] 2021-09-15 15:12
Hey, what does "fishy" mean? :D 

This is a monorepo, so people should not use it and prefer specific packages. Not sure how it got there, so I'm trying to fix it by at least leaving this message, though weirdly processed by packagist, I agree.

I would be better to use multiple packages.

**Comment by Seldaek** [comment] 2021-09-15 15:15
Fixed in https://github.com/composer/packagist/commit/cf0c3ea43b903e5fc7103c0655c01799647cbb36

**Closed by Seldaek** 2021-09-15 15:15 UTC
